// [tag, product name] — matched against opportunity name (case-insensitive)
export const PRODUCTS: [string, string][] = [
  ["People", "Access People"],
  ["Acteol", "Acteol"],
  ["API", "API"],
  ["RWG", "Collins"],
  ["ADC", "Collins"],
  ["Collins Call AI", "Collins"],
  ["Collins", "Collins"],
  ["Connect", "Connect"],
  ["CPL", "CPL"],
  ["Personal", "CPL"],
  ["Early", "EarlyPay"],
  ["Guest Pay", "EPOS"],
  ["EPOS", "EPOS"],
  ["KVS", "EPOS"],
  ["Menu Manager", "EPOS"],
  ["EVO", "EVO"],
  ["Financial", "Financials"],
  ["Flex", "Flexpoints"],
  ["Guest360", "Guest360"],
  ["Guestline", "Guestline"],
  ["Reslinks", "Guestline"],
  ["Integration", "Integration"],
  ["Lightyear", "Lightyear"],
  ["LMS", "LMS"],
  ["Maintain", "Maintain"],
  ["Site", "New Sites"],
  ["Store", "New Sites"],
  ["Orderbee", "Orderbee"],
  ["Genie", "OrderGenie"],
  ["Circle", "Paycircle"],
  ["Troni", "Paytronics"],
  ["PW", "Procure Wizard"],
  ["Wizard", "Procure Wizard"],
  ["Recipes", "Procure Wizard"],
  ["Stock", "Procure Wizard"],
  ["Procure", "Procure Wizard"],
  ["ProNett", "ProNett"],
  ["Kiosk", "QikServe"],
  ["QikServe", "QikServe"],
  ["Diary", "ResDiary"],
  ["RotaReady", "RotaReady"],
  ["Rota", "Rotaready"],
  ["SHR", "SHR"],
  ["Trail", "Trail"],
  ["Wireless", "Wireless Social"],
  ["WS", "Wireless Social"],
  ["PHR", "CPL"],
  ["Renewal", "Renewal"],
  ["Uplift", "Uplift"],
  ["Till", "EPOS"],
  ["CPI", "Uplift"],
  ["Retainer", "Acteol"],
  ["Consult", "Services"],
  ["Screen", "EPOS"],
  ["Loyalty", "Acteol"],
  ["Services", "Services"],
  ["ADE", "ADE"],
  ["Data", "ADE"],
]

export const PRODUCT_GROUPS: Record<string, string[]> = {
  Accom: ["Guest360", "Guestline", "SHR"],
  Account: ["New Sites", "Renewal", "Uplift"],
  EPOS: ["QikServe", "EPOS", "Connect", "OrderGenie", "Orderbee"],
  ERP: ["Financials", "Lightyear"],
  EVO: ["EVO", "Flexpoints", "ADE", "Integration"],
  Guest: ["Collins", "ResDiary", "Acteol", "Paytronics", "Wireless Social"],
  Operations: ["Maintain", "Procure Wizard", "ProNett", "Trail"],
  People: ["RotaReady", "Access People", "CPL", "EarlyPay", "LMS", "Paycircle"],
  Services: ["Services"],
}
